### ISSUE TITLE
Version for Neo4J 2.2.1

### ISSUE THREAD

**Issue by arcecio** [neo4j-contrib/neo4j-library-resources#1]
Hi!

Do you have an ETA for the version for 2.2.1?

Thank you so much!

**Comment by jexp** [comment]
What do you mean? This is a repo for driver author resources

**Comment by cheerfulstoic** [comment]
I just updated the README with a warning at the top in case that was a source of confusion

**Comment by arcecio** [comment]
Whoops. I apologize. Thanks for the clarification!
